name: 'php'

on:
  pull_request:
    paths:
      - '**/*.php'
      - '.github/workflows/php.yml'
      - 'composer.json'
  push:
    paths:
      - '**/*.php'
      - '.github/workflows/php.yml'
      - 'composer.json'

jobs:
  cs:
    uses: bedita/github-workflows/.github/workflows/php-cs.yml@v2
    with:
      php_versions: '["7.4", "8.1", "8.2"]'

  stan:
    uses: bedita/github-workflows/.github/workflows/php-stan.yml@v2
    with:
      php_versions: '["7.4", "8.1", "8.2"]'

  unit:
    name: 'Run unit tests'
    if: "!contains(github.event.commits[0].message, '[skip ci]') && !contains(github.event.commits[0].message, '[ci skip]')"
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        php-version: [7.4, 8.1, 8.2, 8.3]

    steps:
      - name: 'Checkout current revision'
        uses: 'actions/checkout@v4'

      - name: 'Composer config GH token if available'
        run: 'if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi'

      - name: 'Setup PHP'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '${{ matrix.php-version }}'
          tools: 'composer'
          extensions: 'mbstring, intl'

      - name: 'Discover Composer cache directory'
        id: 'cachedir'
        run: echo "path=$(composer global config cache-dir)" >> $GITHUB_OUTPUT

      - name: 'Share Composer cache across runs'
        uses: 'actions/cache@v4'
        with:
          path: '${{ steps.cachedir.outputs.path }}'
          key: "composer-${{ matrix.php-version }}-${{ hashFiles('**/composer.json') }}"
          restore-keys: |
            composer-${{ matrix.php-version }}-
            composer-
      - name: 'Install dependencies with Composer'
        run: 'composer install --prefer-dist --no-interaction'

      - name: 'Run PHPUnit with coverage'
        run: "vendor/bin/phpunit --coverage-clover=${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.php-version }}-clover.xml"

      - name: Check test coverage
        id: test-coverage
        uses: johanvanhelden/gha-clover-test-coverage-check@v1
        with:
          percentage: '85'
          filename: "${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.php-version }}-clover.xml"

      - name: 'Export coverage results'
        uses: 'codecov/codecov-action@v3'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}s
          files: "./${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.php-version }}-clover.xml"
          env_vars: PHP_VERSION

      - name: 'Archive code coverage results'
        uses: 'actions/upload-artifact@v4'
        with:
          name: 'PHP ${{ matrix.php }}'
          path: "${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.php-version }}-clover.xml"
